'use strict';
var app= angular.module('gameApp',['ngRoute','ngAnimate','ksSwiper','ngDialog', 'ngNotify', 'pascalprecht.translate']);

app.config(['$translateProvider', function ($translateProvider) {
  $translateProvider.translations('en', {
    'LOGO' : '/img/logo-en.png',
	'MENU_MAIN': 'Home',
    'MENU_PLAY': 'Play',
    'MENU_ABOUT': 'About',
    'MENU_TOP': 'Top players',
    'MENU_HISTORY': 'History',
    'MENU_LOGOUT': 'Logout',
    'LOGIN_VIA_STEAM' : 'Log in via Steam',
    'FOOTER_POWERED' : 'Powered by Steam, a registered trademark of Valve Corporation.',
    'SIDEBAR_ADD_TO_NICK_TITLE' : 'Add "STEAMWIN.COM" to your Steam nickname and get <span>bonus</span> <span>+5%</span> to your prize ',
    'SIDEBAR_ADD_TO_NICK_DESCR' : 'After nickname change, click "Logout" and then relogin via steam.',
    'SIDEBAR_LAST_WINNER' : 'Last winner:',
    'SIDEBAR_LAST_WINNER_MONEY' : 'Prize:',
    'SIDEBAR_LAST_WINNER_CHANCE' : 'Chance:',
    'SIDEBAR_ONLINE' : 'Currently online',
    'SIDEBAR_PRICES' : 'Prices are presented:',
    'MAIN_JACKPOT_TITLE' : 'MAIN GAME JACKPOT:',
    'MAIN_JACKPOT_DESCR' : 'Players make bets and when maximum item limit is reached, service randomly choose the winner who gets all skins. The larger bet - the bigger chance to win.',
    'MAIN_INFORMERS_GAMES_TODAY' : 'Today games',
    'MAIN_INFORMERS_PLAYERS_TODAY' : 'Today unique players',
    'MAIN_INFORMERS_ITEMS_TODAY' : 'Today items count',
    'MAIN_INFORMERS_MAX_JACKPOT' : 'Maximum jackpot',
    'MAIN_BANNER_TITLE' : 'Take part in prize drawing!<br>Join us in VK and take your knife!',
    'MAIN_BANNER_BUTTON' : 'Get knife',
    'GAME_NUMBER' : 'Game',
    'SOUND_ON' : 'Turn on sound',
    'SOUND_OFF' : 'Turn off sound',
    'BEFORE_TIMER_TEXT' : 'till the prize drawing',
    'ITEMS' : 'items',
    'OR_AFTER' : 'or after',
    'ENTER_GAME_AND_WIN' : 'Join the game and win',
    'YOU_BET' : 'You put',
    'MIN_DEPOSITE' : 'Min.deposite',
    'MAX_ITEMS' : 'Items limit',
    'GAME_ADDITIONAL_TEXT' : 'The larger bet - the bigger prize!',
    'MORE' : 'More',
    'YOUR_CHANCE' : 'Your chance',
    'GAME_STARTED_FIRST' : 'Game started! Make bet first!',
    'GAME_STARTED' : 'Game started! Make bets!',  
    'TOP_GAMERS' : 'Top players',
    'GAMERS_IN_RAITING' : 'Players <br>in raiting',
    'MAX_TODAY_WIN' : 'Maximum <br>jackpot today',
    'TOP_PLACE' : 'Place',
    'TOP_RANK'  : 'Rank',
    'STEAM_NICK' : 'Steam nickname',
    'WIN_COUNT' : 'Win count',
    'WON' : 'Won',
    'ALL_GAMES' : 'All games',
    'CHANCE' : 'Chance',
    'IN_GAME' : 'STAKE IS',
    'ENTER_AND_PLAY' : 'Login and game',
    'PLAYER_WON' : 'Player won',
    'FROM' : 'from',
    'CHOOSE_GAME' : 'Chose room',
    'ENTER_LINK' : 'Attantion! You should enter trade link. ',
    'WHERE_LINK' : 'Where can I get link?',
    'FOR_EXAMPLE' : 'For example',
    'SAVE_LINK' : 'Save link',
    'FOR_SURE' : 'For sure',
    'OPEN_INVENTORY' : 'open inventory',
    'TO_TAKE_PRIZE' : 'in Steam to take prize',
    'ADD_MORE_ITEMS' : 'Bet more',
    'END_GAME' : 'Game ended! Bot takes last bets..',
    'PUTTED' : 'put',
    'END_GAME_STATUS' : 'Game Ended!',
    'ENTER_TRADELINK' : 'Enter trade-offer link',
    'NOW_ONLINE' : 'online now',
    'TODAY_GAMES' : 'games today',
    'TODAY_GAMERS' : 'gamers today',
    'MAXIMUM_JACKPOT' : 'maximum jackpot',
    'SHOW_MAIN_BANNER' : 'display:none;',
    'GAME' : 'GAME',
    'BANK' : 'BANK',
    'GAME_START' : 'Game start'


  });
 
  $translateProvider.translations('ru', {
    'LOGO' : '/img/logo.png',
	'MENU_MAIN': 'Главная',
    'MENU_PLAY': 'Играть',
    'MENU_ABOUT': 'О сайте',
    'MENU_TOP': 'ТОП игроков',
    'MENU_HISTORY': 'История',
    'MENU_LOGOUT': 'Выход',
    'LOGIN_VIA_STEAM' : 'Войти через Steam',
    'FOOTER_POWERED' : 'Powered by Steam, a registered trademark of Valve Corporation.',
    'SIDEBAR_ADD_TO_NICK_TITLE' : 'Добавь в свой ник Steam STEAMWIN.COM и получи <span>бонус</span> к выигрышу <span>+5%</span>',
    'SIDEBAR_ADD_TO_NICK_DESCR' : 'После смены ника, для вступления бонуса в силу, нажмите кнопку Выйти и зайдите на сайт заново.',
    'SIDEBAR_LAST_WINNER' : 'Последний победитель:',
    'SIDEBAR_LAST_WINNER_MONEY' : 'Выигрыш:',
    'SIDEBAR_LAST_WINNER_CHANCE' : 'C шансом:',
    'SIDEBAR_ONLINE' : 'Нас на сайте',
    'SIDEBAR_PRICES' : 'Цены представлены:',
    'MAIN_JACKPOT_TITLE' : 'ГЛАВНЫЙ ДЖЕКПОТ ИГРЫ:',
    'MAIN_JACKPOT_DESCR' : 'Участники вносят ставки, по достижении определенного количества предметов случайным образом выбирается победитель, который получит все скины. Шанс выигрыша зависит от стоимости внесенных скинов.',
    'MAIN_INFORMERS_GAMES_TODAY' : 'Сегодня игр',
    'MAIN_INFORMERS_PLAYERS_TODAY' : 'Сегодня уникальных игроков',
    'MAIN_INFORMERS_ITEMS_TODAY' : 'Сегодня розыграно вещей',
    'MAIN_INFORMERS_MAX_JACKPOT' : 'Максимальный выигрыш',
    'MAIN_BANNER_TITLE' : 'Прими участие в розыграше!<br>Заходи в группу ВК и забери свой нож!',
    'MAIN_BANNER_BUTTON' : 'Получить нож',
    'GAME_NUMBER' : 'Игра',
    'SOUND_ON' : 'Включить звук',
    'SOUND_OFF' : 'Выключить звук',
    'BEFORE_TIMER_TEXT' : 'до начала розыгрыша',
    'ITEMS' : 'предметов',
    'OR_AFTER' : 'или через',
    'ENTER_GAME_AND_WIN' : 'Вступай в игру сейчас и выиграй',
    'YOU_BET' : 'Вы вложили в игру',
    'MIN_DEPOSITE' : 'Мин.ставка',
    'MAX_ITEMS' : 'максимум предметов',
    'GAME_ADDITIONAL_TEXT' : 'Чем выше ставка, тем больше шанс победить.',
    'MORE' : 'Подробнее',
    'YOUR_CHANCE' : 'Ваш шанс',
    'GAME_STARTED_FIRST' : 'Игра началась! Внеси ставку первым!',
    'GAME_STARTED' : 'Игра началась! Вносите ставки!',  
    'TOP_GAMERS' : 'ТОП ИГРОКОВ',
    'GAMERS_IN_RAITING' : 'Игроков <br>в рейтинге',
    'MAX_TODAY_WIN' : 'Максимальный <br>выигрыш сегодня',
    'TOP_PLACE' : 'Место',
    'TOP_RANK'  : 'Звание',
    'STEAM_NICK' : 'Ник в Steam',
    'WIN_COUNT' : 'Количество побед',
    'WON' : 'Выиграл',
    'ALL_GAMES' : 'ВСЕ ИГРЫ',
    'CHANCE' : 'Шанс',
    'IN_GAME' : 'НА КОНУ',
    'ENTER_AND_PLAY' : 'Войти и играть',
    'PLAYER_WON' : 'Победил игрок',
    'FROM' : 'из',
    'CHOOSE_GAME' : 'Выберите игру',
    'ENTER_LINK' : 'Внимание! Необходимо ввести ссылку на обмен. ',
    'WHERE_LINK' : 'Где взять ссылку?',
    'FOR_EXAMPLE' : 'Например',
    'SAVE_LINK' : 'Сохранить ссылку',
    'FOR_SURE' : 'Обязательно',
    'OPEN_INVENTORY' : 'откройте инвентарь',
    'TO_TAKE_PRIZE' : 'в Steam для получения приза!',
    'ADD_MORE_ITEMS' : 'Вложить еще',
    'END_GAME' : 'Игра окончена! Вносятся последние ставки',
    'PUTTED' : 'вложил',
    'END_GAME_STATUS' : 'Игра завершена!',
    'ENTER_TRADELINK' : 'Введите трейд-оффер ссылку',
    'NOW_ONLINE' : 'сейчас онлайн',
    'TODAY_GAMES' : 'игр сегодня',
    'TODAY_GAMERS' : 'игроков сегодня',
    'MAXIMUM_JACKPOT' : 'максимальный выигрыш',
    'SHOW_MAIN_BANNER' : 'display:block;',
    'GAME' : 'ИГРА',
    'BANK' : 'БАНК',
    'GAME_START' : 'Начало игры'
  });
 
  $translateProvider.preferredLanguage('ru');
}]);